### ISSUE TITLE
read through before updating on researcher.one

### ISSUE THREAD

**Issue by ole-peters** [LMLhub/cooperation#1]
@alex-adamou -- I 
* added Lightner to the acknowledgments
* added the parameter values to the figure
* added a python file to researchers.one
* updated the figure to reflect the python file (previously matlab)

I didn't add any of the references Lightner suggested. Athena Aktipis thinks about the problem in the right way, e.g. she doesn't really care whether she's talking about people or cells. But she goes into different modes of cooperation - with record keeping or not etc. If we reference this we may end up having to reference many other considerations too. See if you can find a place to point to her. I like her thinking on these issues.

**Comment by alex-adamou** [comment]
I made some style/clarity edits and toned down some of the emphasis on biology. However, I have not done a root-and-branch conversion to human behaviour (e.g. biomass -> resources, multicellularity -> tribalism?) as that's a bigger job which we should discuss. We could update to RO without doing this, reserving these changes for NHB?

Also, I did not add anything by Aktipis yet.

**Comment by alex-adamou** [comment]
Decided it's worth another round of de-biologising before updating. Little is gained by using specific terms like "biomass" and referring to cells and mutations. General words like "resources" should be just as clear to biologists and will open the message to a larger audience. We use a specific term and then say we are agnostic to its replacement by a more general term, which seems back-to-front.

Multicellularity should be kept, but as an example not a motivation.

**Comment by alex-adamou** [comment]
Abstract and intro de-biologised.

**Comment by ole-peters** [comment]
excellent. And I agree with your earlier comments.

**Comment by alex-adamou** [comment]
Rest of manuscript de-biologised. Almost all instances of "biomass" replaced by "resources". Less emphasis on cellularity. Some other clarifying edits and re-structuring.

**Comment by alex-adamou** [comment]
Cover letter tweaked.
